export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const EDITAR_PROJETO = 'EDITAR_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'

export const ADICIONAR_TAREFA = 'ADICIONAR_TAREFA' 
export const EDITAR_TAREFA = 'EDITAR_TAREFA' 
export const EXCLUIR_TAREFA = 'EXCLUIR_TAREFA'